name: Selenium Tests

on:
  push: # Runs on push events
  schedule: # Runs from Monday to Friday between 17:00 (UTC + 2) 
    - cron: '0 15 * * 1-5'

env:
  PASSWORD: ${{ secrets.PASSWORD }}
  EMAIL: ${{ secrets.EMAIL }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          mkdir -p reports
          pytest --html=reports/index.html 
        continue-on-error: true

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=reports/" >> $GITHUB_ENV

      - name: Setup Pages
        uses: actions/configure-pages@v2
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: reports/

      - name: Deploy to Github pages
        id: deploy
        uses: actions/deploy-pages@v1
